apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 7001
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 8001
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-gateway-vs
spec:
  hosts:
    - "*"
  gateways:
    - hello-gateway
  http:
    - match:
        - port: 7001
      route:
        - destination:
            host: hello-proxy-svc
    - match:
        - port: 8001
      route:
        - destination:
            host: http-hello-svc