apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: http-hello-dr
spec:
  host: http-hello-svc
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-proxy-dr
spec:
  host: hello-proxy-svc
  subsets:
    - name: v1
      labels:
        version: v1