apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-hello-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 7001
        name: http
        protocol: HTTP
      hosts:
        - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-hello-gateway-vs
spec:
  hosts:
    - "*"
  gateways:
    - http-hello-gateway
  http:
    route:
      - destination:
          host: hello-proxy-svc