# hello1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc-reciprocal-hello
  name: hello1-deploy
  labels:
    app: hello1-deploy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1-deploy
      version: v1
  template:
    metadata:
      labels:
        app: hello1-deploy
        version: v1
    spec:
      containers:
        - name: hello-v1-deploy
          image: registry.cn-beijing.aliyuncs.com/asm_repo/grpc_springboot_v1:1.0.0
          env:
            - name: GRPC_HELLO_BACKEND
              value: "hello2-svc.grpc-reciprocal-hello.svc.cluster.local"
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  namespace: grpc-reciprocal-hello
  name: hello1-svc
  labels:
    app: hello1-svc
spec:
  ports:
    - name: grpc-port
      port: 7004
      targetPort: 7001
  selector:
    app: hello1-deploy
---
# hello3
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc-reciprocal-hello
  name: hello3-deploy
  labels:
    app: hello3-deploy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello3-deploy
      version: v1
  template:
    metadata:
      labels:
        app: hello3-deploy
        version: v1
    spec:
      containers:
        - name: hello-v1-deploy
          image: registry.cn-beijing.aliyuncs.com/asm_repo/grpc_springboot_v1:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  namespace: grpc-reciprocal-hello
  name: hello3-svc
  labels:
    app: hello3-svc
spec:
  ports:
    - port: 7001
      name: grpc-port
  selector:
    app: hello3-deploy