apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: consumer
spec:
  hosts:
    - consumer
  http:
    - route:
        - destination:
            host: consumer
            subset: v1
