apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vm-blue-green
  name: hello1-deploy
  labels:
    app: hello1-deploy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1-deploy
      version: v1
  template:
    metadata:
      labels:
        app: hello1-deploy
        version: v1
    spec:
#      serviceAccountName: http-hello-sa
      containers:
        - name: hello-v1-deploy
          image: registry.cn-beijing.aliyuncs.com/asm_repo/http_springboot_v1:1.0.1
          env:
            - name: HTTP_HELLO_BACKEND
              value: "hello2-svc.vm-blue-green.svc.cluster.local"
          ports:
            - containerPort: 8001