Release "flagger" does not exist. Installing it now.
NAME: flagger
LAST DEPLOYED: Mon Oct 19 18:16:32 2020
NAMESPACE: istio-system
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
crd:
  create: false
istio:
  kubeconfig:
    key: kubeconfig
    secretName: istio-kubeconfig
meshProvider: istio
metricsServer: http://ack-prometheus-operator-prometheus:9090

COMPUTED VALUES:
configTracking:
  enabled: true
crd:
  create: false
env: []
eventWebhook: ""
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  pullSecret: null
  repository: weaveworks/flagger
  tag: 1.2.0
ingressAnnotationsPrefix: ""
ingressClass: ""
istio:
  kubeconfig:
    key: kubeconfig
    secretName: istio-kubeconfig
leaderElection:
  enabled: false
  replicaCount: 1
logLevel: info
meshProvider: istio
metricsServer: http://ack-prometheus-operator-prometheus:9090
msteams:
  url: null
nameOverride: ""
namespace: ""
nodeSelector: {}
podAnnotations:
  appmesh.k8s.aws/sidecarInjectorWebhook: disabled
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
podMonitor:
  additionalLabels: {}
  enabled: false
  interval: 15s
  namespace: null
podPriorityClassName: ""
prometheus:
  image: docker.io/prom/prometheus:v2.21.0
  install: false
  retention: 2h
rbac:
  create: true
  pspEnabled: false
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 32Mi
securityContext:
  context:
    readOnlyRootFilesystem: true
    runAsUser: 10001
  enabled: true
selectorLabels: ""
serviceAccount:
  annotations: {}
  create: true
  name: ""
slack:
  channel: null
  url: null
  user: flagger
tolerations: []

HOOKS:
MANIFEST:
---
# Source: flagger/templates/account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagger
  annotations:
  labels:
    helm.sh/chart: flagger-1.2.0
    app.kubernetes.io/name: flagger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: flagger
---
# Source: flagger/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flagger
  labels:
    helm.sh/chart: flagger-1.2.0
    app.kubernetes.io/name: flagger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: flagger
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - configmaps/finalizers
      - secrets
      - secrets/finalizers
      - services
      - services/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - daemonsets/finalizers
      - deployments
      - deployments/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - flagger.app
    resources:
      - canaries
      - canaries/status
      - metrictemplates
      - metrictemplates/status
      - alertproviders
      - alertproviders/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - virtualservices/finalizers
      - destinationrules
      - destinationrules/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - virtualnodes
      - virtualnodes/finalizers
      - virtualrouters
      - virtualrouters/finalizers
      - virtualservices
      - virtualservices/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - split.smi-spec.io
    resources:
      - trafficsplits
      - trafficsplits/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - specs.smi-spec.io
    resources:
      - httproutegroups
      - httproutegroups/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gloo.solo.io
    resources:
      - upstreams
      - upstreams/finalizers
      - upstreamgroups
      - upstreamgroups/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - projectcontour.io
    resources:
      - httpproxies
      - httpproxies/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - nonResourceURLs:
      - /version
    verbs:
      - get
---
# Source: flagger/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flagger
  labels:
    helm.sh/chart: flagger-1.2.0
    app.kubernetes.io/name: flagger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: flagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flagger
subjects:
- name: flagger
  namespace: istio-system
  kind: ServiceAccount
---
# Source: flagger/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
  labels:
    helm.sh/chart: flagger-1.2.0
    app.kubernetes.io/name: flagger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: flagger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: flagger
      app.kubernetes.io/instance: flagger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flagger
        app.kubernetes.io/instance: flagger
      annotations:
        appmesh.k8s.aws/sidecarInjectorWebhook: disabled
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: flagger
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: flagger
                    app.kubernetes.io/instance: flagger
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: kubeconfig
          secret:
            secretName: "istio-kubeconfig"                  
      containers:
        - name: flagger
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10001
          volumeMounts:
            - name: kubeconfig
              mountPath: "/tmp/istio-host"
          image: "weaveworks/flagger:1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8080
          command:
          - ./flagger
          - -log-level=info
          - -mesh-provider=istio
          - -metrics-server=http://ack-prometheus-operator-prometheus:9090
          - -enable-config-tracking=true
          - -slack-user=flagger
          - -kubeconfig-service-mesh=/tmp/istio-host/kubeconfig
          livenessProbe:
            exec:
              command:
              - wget
              - --quiet
              - --tries=1
              - --timeout=4
              - --spider
              - http://localhost:8080/healthz
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - wget
              - --quiet
              - --tries=1
              - --timeout=4
              - --spider
              - http://localhost:8080/healthz
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 32Mi

NOTES:
Flagger installed
