apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-b-vs
spec:
  hosts:
    - hello-b-svc
  http:
    - fault:
        delay:
          fixedDelay: 2s
          percent: 50
      route:
        - destination:
            host: hello-b-svc
            subset: v2
