apiVersion: v1
kind: Service
metadata:
  namespace: http-hello
  name: hello-proxy-svc
  labels:
    app: hello-proxy-deploy
spec:
  ports:
    - port: 7001
      name: http
  selector:
    app: hello-proxy-deploy