apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/service-account.name: hello-sa
  labels:
    app: hello2-svc
  name: hello2-svc
  namespace: hybrid-hello
spec:
  ports:
    - name: http-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: hello2-deploy