apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/service-account.name: http-hello-sa
  labels:
    app: hello-workload
  name: hello2-svc
  namespace: hybrid-hello
spec:
  ports:
    - name: http-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
  type: ClusterIP

