apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v2
  labels:
    app: provider
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
      version: v2
  template:
    metadata:
      labels:
        app: provider
        version: v2
    spec:
      serviceAccountName: grpc-provider
      containers:
        - name: provider
          image: feuyeux/grpc_provider_v2:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6565