apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc-hello
  name: hello3-deploy
  labels:
    app: hello3-deploy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello3-deploy
      version: v1
  template:
    metadata:
      labels:
        app: hello3-deploy
        version: v1
    spec:
      serviceAccountName: grpc-hello-sa
      containers:
        - name: hello-v1-deploy
          image: registry.cn-beijing.aliyuncs.com/asm_repo/grpc_springboot_v1:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
              name: grpc-port