apiVersion: v1
kind: Service
metadata:
  namespace: grpc-hello
  name: hello2-svc
  labels:
    app: hello2-svc
spec:
  ports:
    - port: 7001
      name: grpc-port
  selector:
    app: hello2-deploy