apiVersion: v1
kind: Service
metadata:
  namespace: rsocket-hello
  name: hello1-svc
  labels:
    app: hello1-svc
spec:
  ports:
    - port: 8001
      name: rsocket
  selector:
    app: hello1-deploy