apiVersion: v1
kind: Service
metadata:
  namespace: rsocket-ws-hello
  name: hello2-svc
  labels:
    app: hello2-svc
spec:
  ports:
    - port: 9001
      name: http
  selector:
    app: hello2-deploy