apiVersion: v1
kind: Service
metadata:
  namespace: migrant-hello
  name: hello1-svc
  labels:
    app: hello1-svc
spec:
  ports:
    - name: http
      port: 8004
      targetPort: 8001
      protocol: TCP
  selector:
    app: hello1-deploy